# Generated by Django 4.1.4 on 2022-12-29 12:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('is_verified', models.BooleanField()),
                ('profile_image', models.ImageField(default='images/defalt.png', upload_to='profile_images/')),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
