# Generated by Django 4.1.4 on 2022-12-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/defalt.png', null=True, upload_to='profile_images/'),
        ),
    ]
