# Generated by Django 4.1.4 on 2023-01-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='phone_number',
            field=models.IntegerField(max_length=13, unique=True),
        ),
    ]
