# Generated by Django 4.1.4 on 2023-01-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='accomodation_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
