# Generated by Django 4.1.4 on 2023-01-11 02:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0003_alter_agent_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=13, region=None, unique=True),
        ),
    ]
