# Generated by Django 4.1.4 on 2023-01-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0009_alter_agent_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='state',
            field=models.CharField(choices=[('', 'Select Your State'), ('Abia_state', 'Abia'), ('Adamawa_state', 'Adamawa'), ('Akwa_Ibom_state', 'Akwa Ibom'), ('Anambra_state', 'Anambra'), ('Bauchi_state', 'Bauchi'), ('Bayelsa_state', 'Bayelsa'), ('Benue_state', 'Benue'), ('Borno_state', 'Borno'), ('Cross_River_state', 'Cross River'), ('Delta_state', 'Delta'), ('Eboniyi_state', 'Eboniyi'), ('Edo_state', 'Edo'), ('Ekiti_state', 'Ekiti'), ('Enugu_state', 'Enugu'), ('Gombe_state', 'Gombe'), ('Imo_state', 'Imo'), ('Jigawa_state', 'Jigawa'), ('Kaduna_state', 'Kaduna'), ('Kano_state', 'Kano'), ('Katsina_state', 'Katsina'), ('Kebbi_state', 'Kebbi'), ('Kogi_state', 'Kogi'), ('Kwara_state', 'Kwara'), ('Lagos_state', 'Lagos'), ('Nassarawa_state', 'Nassarawa'), ('Niger_state', 'Niger'), ('Ogun_state', 'Ogun'), ('Ondo_state', 'Ondo'), ('Osun_state', 'Osun'), ('Oyo_state', 'Oyo'), ('Plateau_state', 'Plateau'), ('Rivers_state', 'Rivers'), ('Sokoto_state', 'Sokoto'), ('Taraba_state', 'Taraba'), ('Yobe_state', 'Yobe'), ('Zamfara_state', 'Zamfara'), ('Federal_Capital_Territory', 'Federal Capital Territory')], max_length=30),
        ),
    ]
