price_choices={
    '100000':'$100,000',
    '200000':'$200,000',
    '300000':'$300,000',
    '400000':'$400,000',
    '500000':'$500,000',
    '700000':'$700,000',
    '600000':'$600,000',
    '800000':'$800,000',
    '900000':'$900,000',
    '1000000':'$1M+',

}

state_choices=[
    ('Abia state', 'Abia'),
    ('Adamawa state', 'Adamawa'),
    ('Akwa Ibom state', 'Akwa Ibom'),
    ('Anambra state', 'Anambra'),
    ('Bauchi state', 'Bauchi'),
    ('Bayelsa state', 'Bayelsa'),
    ('Benue state', 'Benue'),
    ('Borno state', 'Borno'),
    ('Cross River state', 'Cross River'),
    ('Delta state', 'Delta'),
    ('Eboniyi state', 'Eboniyi'),
    ('Edo state', 'Edo'),
    ('Ekiti state', 'Ekiti'),
    ('Enugu state', 'Enugu'),
    ('Gombe state', 'Gombe'),
    ('Imo state', 'Imo'),
    ('Jigawa state', 'Jigawa'),
    ('Kaduna state', 'Kaduna'),
    ('Kano state', 'Kano'),
    ('Katsina state', 'Katsina'),
    ('Kebbi state', 'Kebbi'),
    ('Kogi state', 'Kogi'),
    ('Kwara state', 'Kwara'),
    ('Lagos state', 'Lagos'),
    ('Nassarawa state', 'Nassarawa'),
    ('Niger state', 'Niger'),
    ('Ogun state', 'Ogun'),
    ('Ondo state', 'Ondo'),
    ('Osun state', 'Osun'),
    ('Oyo state', 'Oyo'),
    ('Plateau state', 'Plateau'),
    ('Rivers state', 'Rivers'),
    ('Sokoto state', 'Sokoto'),
    ('Taraba state', 'Taraba'),
    ('Yobe state', 'Yobe'),
    ('Zamfara state', 'Zamfara'),
    ('Federal Capital Territory', 'Federal Capital Territory')
]
