# Generated by Django 4.1.4 on 2023-02-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
