# Generated by Django 4.1.4 on 2022-12-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='phone_Number',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
