# Generated by Django 4.1.4 on 2023-04-25 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_newuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='phone_Number',
        ),
    ]
