# Generated by Django 4.1.4 on 2022-12-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Abia_state', 'Abia'), ('Adamawa_state', 'Adamawa'), ('Akwa_Ibom_state', 'Akwa Ibom'), ('Anambra_state', 'Anambra'), ('Bauchi_state', 'Bauchi'), ('Bayelsa_state', 'Bayelsa'), ('Benue_state', 'Benue'), ('Borno_state', 'Borno'), ('Cross_River_state', 'Cross River'), ('Delta_state', 'Delta'), ('Eboniyi_state', 'Eboniyi'), ('Edo_state', 'Edo'), ('Ekiti_state', 'Ekiti'), ('Enugu_state', 'Enugu'), ('Gombe_state', 'Gombe'), ('Imo_state', 'Imo'), ('Jigawa_state', 'Jigawa')], max_length=30)),
                ('school', models.CharField(max_length=70)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Hostel_name', models.CharField(max_length=70)),
                ('Address', models.CharField(max_length=70)),
                ('LGA', models.CharField(max_length=70)),
            ],
        ),
    ]
