# Generated by Django 4.1.4 on 2022-12-29 12:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agents', '0003_alter_agent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('state', models.CharField(choices=[('Abia_state', 'Abia'), ('Adamawa_state', 'Adamawa'), ('Akwa_Ibom_state', 'Akwa Ibom'), ('Anambra_state', 'Anambra'), ('Bauchi_state', 'Bauchi'), ('Bayelsa_state', 'Bayelsa'), ('Benue_state', 'Benue'), ('Borno_state', 'Borno'), ('Cross_River_state', 'Cross River'), ('Delta_state', 'Delta'), ('Eboniyi_state', 'Eboniyi'), ('Edo_state', 'Edo'), ('Ekiti_state', 'Ekiti'), ('Enugu_state', 'Enugu'), ('Gombe_state', 'Gombe'), ('Imo_state', 'Imo'), ('Jigawa_state', 'Jigawa'), ('Kaduna_state', 'Kaduna'), ('Kano_state', 'Kano'), ('Katsina_state', 'Katsina'), ('Kebbi_state', 'Kebbi'), ('Kogi_state', 'Kogi'), ('Kwara_state', 'Kwara'), ('Lagos_state', 'Lagos'), ('Nassarawa_state', 'Nassarawa'), ('Niger_state', 'Niger'), ('Ogun_state', 'Ogun'), ('Ondo_state', 'Ondo'), ('Osun_state', 'Osun'), ('Oyo_state', 'Oyo'), ('Plateau_state', 'Plateau'), ('Rivers_state', 'Rivers'), ('Sokoto_state', 'Sokoto'), ('Taraba_state', 'Taraba'), ('Yobe_state', 'Yobe'), ('Zamfara_state', 'Zamfara'), ('Federal_Capital_Territory', 'Federal Capital Territory')], max_length=30)),
                ('school', models.CharField(max_length=70)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Hostel_name', models.CharField(max_length=70)),
                ('Address', models.CharField(max_length=70)),
                ('LGA', models.CharField(max_length=70)),
                ('image_1', models.ImageField(upload_to='images/')),
                ('image_2', models.ImageField(upload_to='images/')),
                ('image_3', models.ImageField(upload_to='images/')),
                ('image_4', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('date_time_uploaded', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Agents.agent')),
            ],
        ),
    ]
