# Generated by Django 4.1.4 on 2023-01-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accomodation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='image_public_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
