# Generated by Django 4.1.4 on 2023-02-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accomodation', '0002_alter_accomodation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
