# Generated by Django 4.1.4 on 2023-04-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accomodation', '0003_alter_accomodation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='description',
            field=models.TextField(max_length=40),
        ),
    ]
